const $=s=>document.querySelector(s),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const SETTINGS={easy:{name:'やさしい',ms:560,similarity:0},normal:{name:'ふつう',ms:420,similarity:0},hard:{name:'むずかしい',ms:420,similarity:1},master:{name:'名人',ms:320,similarity:2}},COUNTDOWN={3:3,6:5,9:7},STORE='karuta_read_scores_v1',CSV='https://raw.githubusercontent.com/fumiama/OguraHyakuninIsshu/master/%E5%B0%8F%E5%80%89%E7%99%BE%E4%BA%BA%E4%B8%80%E9%A6%96.csv';
let choiceCount=3,difficulty='easy',mode='training',order=[],q=0,answers=[],timer,countdownTimer,readIndex=0,locked=false,current,full='',allPoems=null,upsideDown=false,retryUsed=false,hadMistake=false;
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function loadDB(){try{return JSON.parse(localStorage.getItem(STORE))||{active:'わたし',profiles:{'わたし':[]}}}catch(e){return{active:'わたし',profiles:{'わたし':[]}}}}function saveDB(d){localStorage.setItem(STORE,JSON.stringify(d))}function refreshProfiles(){let d=loadDB(),s=$('#profileSelect');s.innerHTML='';Object.keys(d.profiles).forEach(n=>{let o=document.createElement('option');o.value=o.textContent=n;o.selected=n===d.active;s.appendChild(o)});s.onchange=()=>{let x=loadDB();x.active=s.value;saveDB(x)}}refreshProfiles();
$('#newProfileBtn').onclick=()=>{let n=prompt('ユーザー名を入力してください');if(!n)return;n=n.trim().slice(0,20);if(!n)return;let d=loadDB();d.profiles[n]??=[];d.active=n;saveDB(d);refreshProfiles()};
document.querySelectorAll('.choiceBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choiceBtn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');choiceCount=+b.dataset.count});document.querySelectorAll('.diffBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.diffBtn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');difficulty=b.dataset.diff});document.querySelectorAll('.tabBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabBtn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');mode=b.dataset.mode;$('#modeNote').textContent=mode==='real'?'100首すべてからランダム10問':'一字・二字決まり中心の10問'});
$('#flipBtn').onclick=()=>{upsideDown=!upsideDown;$('#flipBtn').classList.toggle('active',upsideDown);$('#flipBtn').setAttribute('aria-pressed',String(upsideDown));applyFlip()};function applyFlip(){$('#cards').classList.toggle('upside-down',upsideDown)}
function distribute(s){let n=s.length,a=Math.ceil(n/3),b=Math.ceil((n-a)/2);return[s.slice(0,a),s.slice(a,a+b),s.slice(a+b)]}function col(s){let d=document.createElement('div');d.className='poem-col';[...s].forEach(c=>{let x=document.createElement('span');x.className='poem-char';x.textContent=c;d.appendChild(x)});return d}function makeCard(p,correct){let b=document.createElement('button');b.className='card';let f=document.createElement('div');f.className='front';let inn=document.createElement('div');inn.className='card-inner';let g=document.createElement('div');g.className='poem-grid';distribute(p.lower).forEach(s=>g.appendChild(col(s)));inn.appendChild(g);f.appendChild(inn);b.appendChild(f);b.onclick=()=>pick(b,correct);return b}
function chooseDistractors(cur,count,forceRandom=false){let pool=ALL_LOWER.filter(x=>x.lower!==cur.lower),cfg=SETTINGS[difficulty];if(forceRandom||!cfg.similarity)return shuffle(pool).slice(0,count);let first=cur.lower[0],second=cur.lower.slice(0,2),picked=[];if(cfg.similarity>=2)picked.push(...shuffle(pool.filter(x=>x.lower.startsWith(second))));let ids=new Set(picked.map(x=>x.id));picked.push(...shuffle(pool.filter(x=>x.lower.startsWith(first)&&!ids.has(x.id))));picked=picked.slice(0,count);if(picked.length<count){let used=new Set(picked.map(x=>x.id));picked.push(...shuffle(pool.filter(x=>!used.has(x.id))).slice(0,count-picked.length))}return picked}
function parseCSV(text){let lines=text.trim().split(/\r?\n/).slice(1),rows=[];for(let line of lines){let cells=[],cur='',quote=false;for(let ch of line){if(ch==='"')quote=!quote;else if(ch===','&&!quote){cells.push(cur);cur=''}else cur+=ch}cells.push(cur);if(cells.length>=6)rows.push({id:'p'+cells[0],upper:cells[4].replace(/[\s　]/g,''),lower:cells[5].replace(/[\s　]/g,'')})}for(let p of rows){for(let k=1;k<=6;k++){let pre=p.upper.slice(0,k);if(rows.filter(x=>x.upper.startsWith(pre)).length===1){p.key=pre;break}}p.key??=p.upper.slice(0,6);p.rest=p.upper.slice(p.key.length)}return rows}
async function ensure100(){if(allPoems)return allPoems;try{let r=await fetch(CSV);if(!r.ok)throw 0;allPoems=parseCSV(await r.text());return allPoems}catch(e){alert('本番モード用100首データを読み込めませんでした。通信状態を確認してください。');return null}}
async function start(){clearInterval(timer);clearInterval(countdownTimer);if(mode==='real'){let p=await ensure100();if(!p)return;order=shuffle(p).slice(0,10)}else order=shuffle(QUESTION_POOL).slice(0,10);q=0;answers=[];show('readScreen');render(false)}
function beginReading(){if(locked)return;$('#status').textContent='読み進行中';$('#help').textContent='分かった瞬間に札をタップ';step();timer=setInterval(step,SETTINGS[difficulty].ms)}
function buildChoices(forceRandom=false){let ds=chooseDistractors(current,choiceCount-1,forceRandom),opts=shuffle([{lower:current.lower,correct:true},...ds.map(x=>({lower:x.lower,correct:false}))]),box=$('#cards');box.className='cards '+(choiceCount===6?'six':choiceCount===9?'nine':'');box.innerHTML='';opts.forEach(p=>box.appendChild(makeCard(p,p.correct)));applyFlip()}
function startCountdown(){let cd=COUNTDOWN[choiceCount]||3,c=cd;$('#status').textContent='まず札の位置を見てください';$('#stream').textContent=cd;$('#help').textContent=`読み開始まであと${cd}秒`;countdownTimer=setInterval(()=>{c--;if(c>0){$('#stream').textContent=c;$('#help').textContent=`読み開始まであと${c}秒`}else{clearInterval(countdownTimer);$('#stream').textContent='';beginReading()}},1000)}
function render(isRetry){clearInterval(timer);clearInterval(countdownTimer);locked=false;readIndex=0;if(!isRetry){current=order[q];retryUsed=false;hadMistake=false}else retryUsed=true;full=(current.upper||(current.key+current.rest)).replace(/[\s　]/g,'');$('#brand').textContent=`${mode==='real'?'本番':'練習'}・${choiceCount}択・${SETTINGS[difficulty].name}`;$('#progress').textContent=`${q+1} / 10`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#retryBtn').classList.remove('show');$('#retryBtn').disabled=false;buildChoices(isRetry);startCountdown()}
function step(){if(locked)return;if(readIndex<full.length)readIndex++;let shown=full.slice(0,readIndex),k=current.key.length;$('#stream').innerHTML=`<span class="kimari">${shown.slice(0,Math.min(k,shown.length))}</span>${shown.slice(k)}`;if(readIndex>=full.length){clearInterval(timer);$('#help').textContent='最後まで読まれました。分かれば札をタップ'}}
function pick(btn,correct){if(locked)return;if(!correct){hadMistake=true;btn.classList.add('wrong');$('#feedback').className='feedback ng';$('#feedback').textContent=retryUsed?'× ちがう札です':'× ちがう札です。やり直せます';if(!retryUsed)$('#retryBtn').classList.add('show');setTimeout(()=>btn.classList.remove('wrong'),450);return}locked=true;clearInterval(timer);clearInterval(countdownTimer);$('#retryBtn').classList.remove('show');btn.classList.add('correct');let chars=Math.max(1,readIndex),extra=chars-current.key.length;answers.push({p:current,chars,extra,shown:full.slice(0,chars),mistake:hadMistake,retry:retryUsed});$('#feedback').className='feedback ok';$('#feedback').textContent=extra===0?`◎ 決まり字「${current.key}」で取れました！`:extra>0?`○「${full.slice(0,chars)}」で取得 ／ ＋${extra}文字`:`○ 決まり字より${-extra}文字早い`;setTimeout(()=>{q++;q>=10?finish():render(false)},900)}
$('#retryBtn').onclick=()=>{if(retryUsed)return;$('#retryBtn').classList.remove('show');$('#retryBtn').disabled=true;render(true)};
function finish(){let valid=answers.filter(a=>a.extra>=0),avg=valid.length?valid.reduce((s,a)=>s+a.extra,0)/valid.length:0,masters=answers.filter(a=>a.extra===0).length;$('#mainResult').textContent=`平均 ＋${avg.toFixed(1)}文字`;$('#summary').innerHTML=`${mode==='real'?'本番':'トレーニング'}・${choiceCount}択・${SETTINGS[difficulty].name}<br>決まり字ぴったり：<b>${masters} / 10</b>`;let list=$('#resultList');list.innerHTML='';answers.forEach((a,i)=>{let d=document.createElement('div');d.className='read-row';d.innerHTML=`<div><b>${i+1}. ${a.p.key}</b><div style="font-size:11px;color:#777">${a.shown} でタップ${a.retry?'・やり直し使用':''}</div></div><div class="${a.extra===0?'good':'late'}">${a.extra===0?'決まり字':`＋${a.extra}文字`}</div>`;list.appendChild(d)});let db=loadDB(),rec={date:new Date().toISOString(),mode,choices:choiceCount,diff:difficulty,avg:+avg.toFixed(2),masters,items:answers.map(a=>({id:a.p.id,key:a.p.key,extra:a.extra,retry:a.retry,mistake:a.mistake}))};db.profiles[db.active]??=[];db.profiles[db.active].push(rec);saveDB(db);show('resultScreen')}
function avgOf(arr){return arr.length?arr.reduce((s,x)=>s+x,0)/arr.length:null}
function renderTrend(h){let el=$('#trendWrap'),rows=h.slice(-10);if(rows.length<2){el.innerHTML='<div class="trend-empty">2回以上プレイすると推移が表示されます</div>';return}let vals=rows.map(r=>Number(r.avg)||0),max=Math.max(4,...vals),min=0,w=320,hg=112,p=15;let pts=vals.map((v,i)=>{let x=p+(w-2*p)*(i/(vals.length-1)),y=p+(hg-2*p)*((v-min)/(max-min||1));return[x,hg-y+p/2]}),poly=pts.map(p=>p.join(',')).join(' ');let dots=pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3.5" fill="#315f42"><title>＋${vals[i].toFixed(1)}文字</title></circle>`).join('');el.innerHTML=`<svg class="trend-svg" viewBox="0 0 ${w} ${hg}" preserveAspectRatio="none"><line x1="${p}" y1="${hg-p}" x2="${w-p}" y2="${hg-p}" stroke="#ddd5c9"/><line x1="${p}" y1="${p}" x2="${p}" y2="${hg-p}" stroke="#eee7dc"/><polyline points="${poly}" fill="none" stroke="#315f42" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>${dots}<text x="${p}" y="${hg-1}" font-size="8" fill="#8b8378">古い</text><text x="${w-p}" y="${hg-1}" font-size="8" fill="#8b8378" text-anchor="end">最新</text></svg>`}
function renderChoiceBars(h){let box=$('#choiceBars');box.innerHTML='';[3,6,9].forEach(c=>{let vals=h.filter(r=>r.choices===c).map(r=>Number(r.avg)).filter(Number.isFinite),avg=avgOf(vals),score=avg===null?0:Math.max(0,Math.min(100,100-(avg/6*100))),d=document.createElement('div');d.className='choice-row';d.innerHTML=`<div class="choice-label">${c}択</div><div class="bar-track"><div class="bar-fill" style="width:${score}%"></div></div><div class="choice-value">${avg===null?'未挑戦':'＋'+avg.toFixed(1)}</div>`;box.appendChild(d)})}
function aggregateKeys(items){let m=new Map;items.forEach(x=>{let k=x.key||x.id;if(!k)return;if(!m.has(k))m.set(k,{key:k,vals:[],tries:0,master:0});let v=m.get(k);v.tries++;if(Number.isFinite(x.extra)){v.vals.push(x.extra);if(x.extra===0)v.master++}});return[...m.values()].map(v=>({...v,avg:v.vals.length?avgOf(v.vals):99}));}
function renderMap(items){let box=$('#mapGrid');box.innerHTML='';let byId=new Map,byKey=new Map;items.forEach(x=>{if(x.id)byId.set(String(x.id),x);if(x.key)byKey.set(x.key,x)});for(let i=1;i<=100;i++){let related=items.filter(x=>String(x.id)==='p'+i),vals=related.map(x=>x.extra).filter(Number.isFinite),avg=avgOf(vals),cell=document.createElement('div');cell.className='map-cell';if(avg!==null){cell.classList.add('seen');if(avg<=2)cell.classList.add('good');if(avg<=.75)cell.classList.add('master')}cell.textContent=i;cell.title=avg===null?`${i}番 未挑戦`:`${i}番 平均＋${avg.toFixed(1)}文字`;box.appendChild(cell)}}
function renderRanks(items){let a=aggregateKeys(items).filter(x=>x.vals.length);let best=[...a].sort((x,y)=>x.avg-y.avg).slice(0,3),weak=[...a].sort((x,y)=>y.avg-x.avg).slice(0,3);function fill(id,arr){let b=$(id);b.innerHTML=arr.length?'':'<div style="font-size:10px;color:#999">データなし</div>';arr.forEach(x=>{let d=document.createElement('div');d.className='rank-item';d.innerHTML=`<span class="rank-key">${x.key}</span><span>＋${x.avg.toFixed(1)}</span>`;b.appendChild(d)})}fill('#bestList',best);fill('#weakList',weak)}
function dashboard(){let db=loadDB(),name=db.active,h=db.profiles[name]||[],all=h.flatMap(x=>x.items||[]),valid=all.filter(x=>Number.isFinite(x.extra)&&x.extra>=0),avg=valid.length?avgOf(valid.map(x=>x.extra)):null,masters=all.filter(x=>x.extra===0).length,masterPct=all.length?Math.round(masters/all.length*100):0,retries=all.filter(x=>x.retry).length,retryPct=all.length?Math.round(retries/all.length*100):0;$('#dashTitle').textContent=`${name} の成長`;$('#dPlays').textContent=h.length;$('#dQuestions').textContent=all.length;$('#dAvg').textContent=avg===null?'—':'＋'+avg.toFixed(1)+'文字';$('#dMaster').textContent=masterPct+'%';$('#dRetry').textContent=retryPct+'%';$('#masterRing').style.background=`conic-gradient(var(--green) ${masterPct*3.6}deg,#e5dfd4 0deg)`;let recent=h.slice(-5),prior=h.slice(-10,-5),ra=avgOf(recent.map(x=>Number(x.avg)).filter(Number.isFinite)),pa=avgOf(prior.map(x=>Number(x.avg)).filter(Number.isFinite));if(ra===null)$('#dDelta').textContent='プレイすると成長が表示されます。';else if(pa===null)$('#dDelta').innerHTML=`現在は平均 <b>＋${ra.toFixed(1)}文字</b>。ここから記録が育ちます。`;else{let delta=pa-ra;if(Math.abs(delta)<.05)$('#dDelta').textContent='最近の反応タイミングは安定しています。';else if(delta>0)$('#dDelta').innerHTML=`直前5回より <span class="delta-up">${delta.toFixed(1)}文字早く</span> 取れています。`;else $('#dDelta').innerHTML=`直前5回より <span class="delta-down">${Math.abs(delta).toFixed(1)}文字遅め</span>。復習チャンスです。`}renderTrend(h);renderChoiceBars(h);renderMap(all);renderRanks(all);let box=$('#history');box.innerHTML=h.length?'':'まだ成績がありません。';[...h].reverse().slice(0,10).forEach(r=>{let d=document.createElement('div');d.className='hist',dt=new Date(r.date);d.innerHTML=`<b>${r.mode==='real'?'本番':'練習'} ${r.choices}択・${SETTINGS[r.diff]?.name||r.diff}</b><br>${dt.toLocaleDateString('ja-JP')} ${dt.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}　平均＋${r.avg}文字　決まり字 ${r.masters}/10`;box.appendChild(d)});show('dashScreen')}
$('#startBtn').onclick=start;$('#againBtn').onclick=start;$('#homeBtn').onclick=$('#dashHomeBtn').onclick=()=>show('startScreen');$('#dashBtn').onclick=$('#resultDashBtn').onclick=dashboard;