(()=>{
const DB_NAME='karuta_local_audio_v1',STORE='tracks',PREF='karuta_audio_enabled_v1';
let dbPromise=null,audio=new Audio(),currentUrl=null,enabled=localStorage.getItem(PREF)==='1',statusEl=null,toggleBtn=null,unlocked=false;
audio.preload='auto';
function norm(s){return String(s||'').replace(/[\s　]/g,'').replace(/ゐ/g,'い').replace(/ゑ/g,'え')}
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'n'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
async function putTrack(n,blob,name){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({n,blob,name});tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function getTrack(n){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(n);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function countTracks(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).count();r.onsuccess=()=>res(r.result||0);r.onerror=()=>rej(r.error)})}
async function clearTracks(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
function fileNumber(name){const ms=[...String(name).matchAll(/\d{1,3}/g)].map(m=>+m[0]).filter(n=>n>=1&&n<=100);return ms.length?ms[0]:null}
async function importFiles(files){let arr=[...files].filter(f=>/audio|mp3/i.test(f.type)||/\.mp3$/i.test(f.name));if(!arr.length)return;let parsed=arr.map(f=>({f,n:fileNumber(f.name)})),unique=new Set(parsed.filter(x=>x.n).map(x=>x.n));if(arr.length===100&&(unique.size<90)){parsed=arr.sort((a,b)=>a.name.localeCompare(b.name,'ja',{numeric:true})).map((f,i)=>({f,n:i+1}))}
let done=0;for(const x of parsed){if(!x.n)continue;await putTrack(x.n,x.f,x.f.name);done++;updateStatus(`保存中… ${done}曲`)}await prepareUnlock();updateStatus();if(done)alert(`${done}曲をこの端末内に保存しました。\n音源ファイルはGitHubには送信されません。`)}
function correctLower(){const c=document.querySelector('#cards .card[data-correct="1"]');if(!c)return'';return norm([...c.querySelectorAll('.poem-char')].map(x=>x.textContent).join(''))}
function poemNumberFromScreen(){const lower=correctLower();if(!lower||!window.ALL_LOWER)return null;let i=window.ALL_LOWER.findIndex(x=>norm(x.lower)===lower);if(i>=0)return i+1;const head=lower.slice(0,8);i=window.ALL_LOWER.findIndex(x=>norm(x.lower).startsWith(head));return i>=0?i+1:null}
function stop(){try{audio.pause();audio.currentTime=0}catch(e){}if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}}
async function playCurrent(){if(!enabled)return;const n=poemNumberFromScreen();if(!n)return;try{const rec=await getTrack(n);if(!rec)return;stop();currentUrl=URL.createObjectURL(rec.blob);audio.src=currentUrl;audio.currentTime=0;await audio.play()}catch(e){console.warn('karuta audio',e);updateStatus('音声を再生できません。音量・Safari設定を確認してください。')}}
async function prepareUnlock(){try{const rec=await getTrack(1);if(!rec)return;const u=URL.createObjectURL(rec.blob);audio.src=u;audio.load();setTimeout(()=>URL.revokeObjectURL(u),3000)}catch(e){}}
function unlock(){if(unlocked)return;unlocked=true;try{const p=audio.play();if(p&&p.then)p.then(()=>{audio.pause();audio.currentTime=0}).catch(()=>{})}catch(e){}}
async function updateStatus(custom){if(!statusEl)return;if(custom){statusEl.textContent=custom;return}const n=await countTracks().catch(()=>0);statusEl.textContent=n?`この端末に ${n}/100曲保存済み`:'MP3はまだこの端末に保存されていません';if(toggleBtn){toggleBtn.disabled=!n;toggleBtn.textContent=enabled&&n?'読み上げ ON':'読み上げ OFF';toggleBtn.classList.toggle('on',enabled&&n)}}
function installUI(){const panel=document.querySelector('#startScreen .panel');if(!panel||document.querySelector('#audioSetup'))return false;const wrap=document.createElement('div');wrap.id='audioSetup';wrap.innerHTML=`<div class="audio-box"><div class="audio-head"><b>🎧 読手MP3</b><button id="audioToggle" type="button">読み上げ OFF</button></div><div id="audioStatus" class="audio-status"></div><div class="audio-actions"><label class="audio-import">MP3を読み込む<input id="audioFiles" type="file" accept="audio/mpeg,.mp3" multiple></label><button id="audioClear" type="button">削除</button></div><div class="audio-note">購入・入手したMP3をこの端末だけに保存して再生します。音源はGitHubへアップロードしません。</div></div>`;const start=document.querySelector('#startBtn');panel.insertBefore(wrap,start);const st=document.createElement('style');st.textContent=`.audio-box{margin:12px 0 2px;background:#fffaf0;border:1px solid #eadfcd;border-radius:13px;padding:10px}.audio-head{display:flex;justify-content:space-between;align-items:center;font-size:12px}.audio-head button{border:1px solid #cfc7bb;background:#fff;color:#625d55;border-radius:999px;padding:6px 10px;font-size:10px;font-weight:900}.audio-head button.on{background:#315f42;color:#fff;border-color:#315f42}.audio-status{font-size:10px;color:#746f66;margin:6px 0}.audio-actions{display:grid;grid-template-columns:1fr auto;gap:6px}.audio-import,.audio-actions button{border:0;border-radius:9px;padding:9px 8px;font-size:11px;font-weight:900;text-align:center}.audio-import{background:#a77a20;color:#fff}.audio-import input{display:none}.audio-actions button{background:#ece7de;color:#635d54}.audio-note{font-size:8px;color:#8a8277;line-height:1.45;margin-top:6px}`;document.head.appendChild(st);statusEl=document.querySelector('#audioStatus');toggleBtn=document.querySelector('#audioToggle');document.querySelector('#audioFiles').onchange=e=>importFiles(e.target.files);toggleBtn.onclick=async()=>{const n=await countTracks().catch(()=>0);if(!n)return;enabled=!enabled;localStorage.setItem(PREF,enabled?'1':'0');updateStatus()};document.querySelector('#audioClear').onclick=async()=>{if(!confirm('この端末に保存した読手MP3を削除しますか？'))return;stop();await clearTracks();enabled=false;localStorage.setItem(PREF,'0');updateStatus()};updateStatus();prepareUnlock();return true}
function hookGame(){if(typeof window.beginReading!=='function'){setTimeout(hookGame,100);return}const oldBegin=window.beginReading;window.beginReading=function(){const r=oldBegin.apply(this,arguments);playCurrent();return r};if(typeof window.clearGameTimers==='function'){const oldClear=window.clearGameTimers;window.clearGameTimers=function(){stop();return oldClear.apply(this,arguments)}}if(typeof window.opponentTake==='function'){const oldOpp=window.opponentTake;window.opponentTake=function(){stop();return oldOpp.apply(this,arguments)}}document.addEventListener('click',e=>{if(e.target.closest('#cards .card'))stop()},true);document.querySelector('#startBtn')?.addEventListener('click',unlock,true)}
function init(){if(!installUI()){setTimeout(init,100);return}hookGame()}
window.KarutaLocalAudio={playCurrent,stop,countTracks};init();
})();