(function (global) {
  "use strict";

  const links = {
    autumn: {
      id: "autumn",
      name: "秋風共鳴",
      short: "秋",
      color: "#d98745",
      description: "通常攻撃の威力が上がる",
      poemNos: [1, 5, 10, 16, 17, 23, 24, 32, 47, 69, 70, 71, 79, 87],
    },
    moon: {
      id: "moon",
      name: "月影共鳴",
      short: "月",
      color: "#8fb4d8",
      description: "攻撃時のMP消費を抑える",
      poemNos: [7, 21, 23, 30, 31, 36, 57, 59, 60, 68, 79, 81, 86],
    },
    love: {
      id: "love",
      name: "恋歌共鳴",
      short: "恋",
      color: "#d66f8c",
      description: "攻撃のたびにHPを回復する",
      poemNos: [
        13, 14, 18, 19, 20, 25, 26, 27, 30, 38, 39, 40, 41, 42, 43, 44, 46, 48,
        49, 50, 51, 52, 53, 54, 58, 63, 65, 72, 74, 77, 80, 82, 85, 88, 89, 90,
        92, 97,
      ],
    },
    water: {
      id: "water",
      name: "水脈共鳴",
      short: "水",
      color: "#5ca7b7",
      description: "怪異から受けるダメージを減らす",
      poemNos: [
        6, 13, 17, 20, 27, 32, 42, 46, 48, 58, 61, 64, 72, 73, 77, 78, 80, 81,
        88, 92, 98,
      ],
    },
    sacred: {
      id: "sacred",
      name: "神代共鳴",
      short: "祈",
      color: "#d6b65f",
      description: "一首接続でHPとMPを回復する",
      poemNos: [
        2, 4, 8, 9, 12, 15, 16, 18, 21, 22, 28, 34, 35, 37, 45, 51, 62, 66, 84,
        94, 95, 96, 100,
      ],
    },
  };

  // 小倉百人一首1〜100番の決まり字。既存data.jsはトレーニング対象49首のみ
  // 決まり字を持つため、RPGで全100首を安定して使えるよう章データ側に固定する。
  const decisionKeys = [
    "あきの",
    "はるす",
    "あし",
    "たご",
    "おく",
    "かさ",
    "あまの",
    "わがい",
    "はなの",
    "これ",
    "わたのはらや",
    "あまつ",
    "つく",
    "みち",
    "きみがためは",
    "たち",
    "ちは",
    "す",
    "なにはが",
    "わび",
    "いまこ",
    "ふ",
    "つき",
    "この",
    "なにし",
    "を",
    "みかの",
    "やまざ",
    "こころあ",
    "ありあ",
    "あさぼらけあ",
    "やまが",
    "ひさ",
    "たれ",
    "ひとは",
    "なつ",
    "しら",
    "わすら",
    "あさぢ",
    "しの",
    "こひ",
    "ちぎりき",
    "あひ",
    "あふ",
    "あはれ",
    "ゆら",
    "やへ",
    "かぜを",
    "みかき",
    "きみがためを",
    "かく",
    "あけ",
    "なげき",
    "わすれ",
    "たき",
    "あらざ",
    "め",
    "ありま",
    "やす",
    "おほえ",
    "いに",
    "よを",
    "いまは",
    "あさぼらけう",
    "うら",
    "もろ",
    "はるの",
    "こころに",
    "あらし",
    "さ",
    "ゆふ",
    "おと",
    "たか",
    "うか",
    "ちぎりお",
    "わたのはらこ",
    "せ",
    "あはぢ",
    "あきか",
    "ながか",
    "ほ",
    "おも",
    "よのなかよ",
    "ながら",
    "よも",
    "なげけ",
    "む",
    "なにはえ",
    "たま",
    "みせ",
    "きり",
    "わがそ",
    "よのなかは",
    "みよ",
    "おほけ",
    "はなさ",
    "こぬ",
    "かぜそ",
    "ひとも",
    "もも",
  ];

  const monsters = [
    {
      id: "hakumen",
      order: 1,
      name: "白面の野狐",
      reading: "はくめんのやこ",
      epithet: "月下に尾を曳く、忘却の獣",
      archetype: "fox",
      palette: ["#d9d6ce", "#7f756c", "#d24a36"],
      sealPoems: [17, 5, 87],
      place: "すすき野",
      story:
        "歌人の記憶を喰らい、白い尾へ変えてきた。三つの尾に決まり字が灯る。",
      intro: "草むらの奥で、三本の尾が月を隠した。",
      threat: "夜明けまでに、すすき野から『大切な人を呼ぶ歌』が消えてしまう。",
    },
    {
      id: "sumikurai",
      order: 2,
      name: "墨喰らい",
      reading: "すみくらい",
      epithet: "消された文字から生まれた影",
      archetype: "ink",
      palette: ["#171924", "#526078", "#cf4d3c"],
      sealPoems: [32, 75, 18],
      place: "破れ文庫",
      story:
        "料紙から文字だけを吸い上げる。腹の奥では、奪われた歌が黒く渦巻く。",
      intro: "墨の染みが床を這い、ゆっくりと顔をつくった。",
      threat: "夜明けまでに、文庫に残る歌人の名がすべて白紙になる。",
    },
    {
      id: "tsukibami",
      order: 3,
      name: "月蝕みの鴉",
      reading: "つきはみのからす",
      epithet: "夜空の歌を啄む黒翼",
      archetype: "crow",
      palette: ["#151a2a", "#67759a", "#e0b75b"],
      sealPoems: [57, 30, 36],
      place: "月見の丘",
      story:
        "月を詠んだ歌を憎み、光の言葉を一字ずつ啄む。羽ばたくたび夜が深くなる。",
      intro: "欠けた月を背に、巨大な翼が音もなく開いた。",
      threat: "月を喰い切れば、月を詠んだ十三首は二度と読めなくなる。",
    },
    {
      id: "tomoshibigumo",
      order: 4,
      name: "灯蜘蛛",
      reading: "ともしびぐも",
      epithet: "灯籠に巣を張る八脚の怪",
      archetype: "spider",
      palette: ["#2b1720", "#864434", "#efb45e"],
      sealPoems: [69, 54, 51],
      place: "古橋",
      story: "消えた灯の数だけ脚を増やす。腹に浮かぶ三首が巣を支えている。",
      intro: "灯籠の火が消える。暗闇に八つの眼だけが残った。",
      threat: "三つの灯が消えれば、橋を渡る者の帰る記憶まで巣に絡め取られる。",
    },
    {
      id: "sakasawara",
      order: 5,
      name: "逆さ童",
      reading: "さかさわらべ",
      epithet: "天井を歩く無顔の稚児",
      archetype: "child",
      palette: ["#c8b38e", "#473449", "#8e2f37"],
      sealPoems: [34, 12, 95],
      place: "空寝殿",
      story:
        "誰にも読まれなくなった歌を、逆さ言葉で囁き続ける。振り向くと顔を奪われる。",
      intro: "梁が軋む。頭上から小さな笑い声が降ってきた。",
      threat: "声に振り向いた者は、顔と名前を歌から奪われる。",
    },
    {
      id: "mizukagami",
      order: 6,
      name: "水鏡の大蛇",
      reading: "みずかがみのおろち",
      epithet: "映る心を呑み込む川の主",
      archetype: "serpent",
      palette: ["#32545b", "#79a3a5", "#d8c274"],
      sealPoems: [61, 77, 46],
      place: "鏡川",
      story:
        "水面に映った未練を餌にする。鱗の一枚ごとに、忘れられた下の句が眠る。",
      intro: "川面の月が二つに割れ、青い巨体が鎌首をもたげた。",
      threat: "鏡川が曇り切れば、都の人々は愛した者の面影を失う。",
    },
    {
      id: "momijioni",
      order: 7,
      name: "紅葉狩りの鬼",
      reading: "もみじがりのおに",
      epithet: "散る歌を鎧う朱の剛鬼",
      archetype: "oni",
      palette: ["#7a2626", "#b64b32", "#e1a95b"],
      sealPoems: [24, 26, 70],
      place: "龍田の坂",
      story:
        "美しい秋の歌だけを集め、鎧として纏う。怒りが満ちると山全体が紅に染まる。",
      intro: "紅葉の渦が割れ、金棒を引きずる音が近づいた。",
      threat: "鎧が完成すれば、龍田の紅葉と秋の歌は美しいまま永遠に死ぬ。",
    },
    {
      id: "nemurijika",
      order: 8,
      name: "夢喰み鹿",
      reading: "ゆめくみじか",
      epithet: "眠りを渡る金角の獣",
      archetype: "deer",
      palette: ["#574536", "#b69a72", "#e0c66f"],
      sealPoems: [10, 21, 33],
      place: "鹿鳴の庭",
      story:
        "人の夢から懐かしい歌を盗む。角に吊られた鈴が鳴ると、記憶がひとつ消える。",
      intro: "霧の向こうで鈴が鳴り、黄金の角が夜を裂いた。",
      threat: "次の鈴が鳴れば、眠る子どもたちは家族の声を思い出せない。",
    },
    {
      id: "ayanukiga",
      order: 9,
      name: "綾裂き蛾",
      reading: "あやさきが",
      epithet: "十二単を喰む宵闇の翅",
      archetype: "moth",
      palette: ["#665071", "#b48a9e", "#e7c978"],
      sealPoems: [9, 19, 89],
      place: "装束蔵",
      story: "重ねの色目を翅へ写し取る。舞う鱗粉は歌の順序を狂わせる。",
      intro: "裂けた綾絹が宙へ浮き、巨大な翅へと姿を変えた。",
      threat: "十二の翅が揃えば歌の順序がほどけ、百首は意味を失う。",
    },
    {
      id: "kanesemukade",
      order: 10,
      name: "鐘背百足",
      reading: "かねせむかで",
      epithet: "百の足で時を刻む鉄殻",
      archetype: "centipede",
      palette: ["#3c3028", "#907052", "#d69a45"],
      sealPoems: [73, 98, 66],
      place: "時鐘楼",
      story:
        "古鐘を背負い、鳴るたび一首を過去へ葬る。硬い節の隙間に三枚の封印が見える。",
      intro: "地の底で鐘が鳴る。無数の脚が石畳を叩き始めた。",
      threat: "鐘が百度鳴れば、百首は生まれる前の時へ葬られる。",
    },
  ];

  const boss = {
    id: "michinaga",
    order: 11,
    boss: true,
    name: "望月卿・藤原道長",
    reading: "もちづききょう・ふじわらのみちなが",
    epithet: "百首に選ばれなかった、満月の権力者",
    archetype: "boss",
    palette: ["#2d203a", "#8f6e9e", "#e5c15f"],
    sealPoems: [7, 57, 81],
    place: "望月殿",
    story:
      "栄華を極めながら百首に名を刻まれなかった男。歌の記憶を奪い、永遠の満月に自らの名を残そうとする。",
    intro: "御簾が上がる。満月を背負った男が、静かにこちらを見下ろした。",
    threat: "望月が満ち切れば、百首すべてが道長ただ一人の歌へ書き換わる。",
  };

  global.HYAKUSHU_IBUN_DATA = {
    version: 1,
    links,
    decisionKeys,
    monsters,
    boss,
    chapter: {
      id: "heian",
      name: "第一章　平安編",
      subtitle: "望月に喰われた歌",
      normalBattlesPerRun: 4,
    },
  };
})(typeof window !== "undefined" ? window : globalThis);
