(()=>{
const $=s=>document.querySelector(s);
function injectStyles(){const st=document.createElement('style');st.textContent=`
.voice-entry{width:100%;border:0;border-radius:13px;background:#a77a20;color:#fff;padding:14px 8px;font-size:17px;font-weight:900;margin-top:9px;box-shadow:0 5px 14px rgba(167,122,32,.16)}
.voice-page{display:none;min-height:calc(100dvh - 24px)}.voice-page.active{display:block}.voice-panel{background:rgba(255,255,255,.7);border-radius:18px;padding:16px 13px;min-height:calc(100dvh - 30px);box-shadow:0 8px 24px rgba(0,0,0,.07)}
.voice-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.voice-back{border:0;background:#fff;color:#5f5a52;border-radius:10px;padding:8px 11px;font-weight:800}.voice-progress{font-size:12px;color:#746f66;font-weight:800}.voice-kicker{text-align:center;color:#a77a20;font-size:10px;font-weight:900;letter-spacing:.17em;margin-top:4px}.voice-title{text-align:center;font-size:23px;font-weight:900;margin:4px 0}.voice-lead{text-align:center;color:#746f66;font-size:12px;line-height:1.55;margin-bottom:11px}
.voice-card{background:#fffaf0;border-radius:18px;padding:18px 12px;text-align:center;min-height:330px;display:flex;flex-direction:column;justify-content:center;align-items:center;box-shadow:inset 0 0 0 1px #efe5d5}.voice-step{font-size:11px;color:#746f66;font-weight:900;letter-spacing:.08em}.voice-key{font-family:"Yu Mincho","Hiragino Mincho ProN",serif;font-size:76px;line-height:1;font-weight:900;color:#315f42;margin:10px 0}.voice-arrow{font-size:28px;color:#a77a20;font-weight:900;margin:-2px 0 4px}.voice-lower{font-family:"Yu Mincho","Hiragino Mincho ProN",serif;font-size:25px;font-weight:800;line-height:1.55;max-width:330px}.voice-lower.masked{color:#b9b1a5;letter-spacing:.1em}.voice-cue{font-size:15px;color:#5d574f;font-weight:800;margin-top:10px}.voice-timer{font-size:12px;color:#8b8378;margin-top:7px;min-height:18px}
.voice-actions{display:grid;grid-template-columns:1fr;gap:8px;margin-top:10px}.voice-main{border:0;border-radius:13px;background:#315f42;color:#fff;padding:14px;font-weight:900;font-size:16px}.voice-main.gold{background:#a77a20}.voice-self{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.voice-self button{border:1px solid #d8d0c4;background:#fff;border-radius:12px;padding:12px 4px;font-weight:900;font-size:13px}.voice-self .yes{color:#16804d;border-color:#9dc8ae}.voice-self .maybe{color:#a77a20;border-color:#d9c28c}.voice-self .no{color:#b43b30;border-color:#d9a6a1}.voice-note{text-align:center;color:#746f66;font-size:10px;line-height:1.55;margin-top:9px}
.voice-summary{display:none;text-align:center}.voice-summary.show{display:block}.voice-big{font-size:48px;font-weight:900;color:#315f42;margin:8px 0}.voice-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.voice-stat{background:#fff;border-radius:12px;padding:11px 4px}.voice-stat b{display:block;font-size:23px}.voice-stat span{font-size:9px;color:#746f66}.voice-review{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;margin:12px 0}.voice-dot{border-radius:8px;padding:9px 1px;background:#ece7de;font-family:"Yu Mincho",serif;font-weight:900;font-size:17px}.voice-dot.ok{background:#315f42;color:#fff}.voice-dot.mid{background:#d7c083;color:#fff}.voice-dot.ng{background:#b66a61;color:#fff}
@media(max-width:420px){.voice-panel{padding:12px 9px}.voice-card{min-height:305px;padding:14px 9px}.voice-key{font-size:68px}.voice-lower{font-size:22px}.voice-title{font-size:21px}}
`;document.head.appendChild(st)}

const base=()=>window.QUESTION_POOL.filter(p=>p.key.length===1).slice(0,7);
let page,queue=[],index=0,current=null,phase='see',results={},requeues={},autoTimer=null;
function clean(s){return String(s||'').replace(/[\s　]/g,'')}
function shortLower(p){const s=clean(p.lower);return s.length>11?s.slice(0,11)+'…':s}
function makePage(){page=document.createElement('section');page.id='voiceScreen';page.className='voice-page';page.innerHTML=`<div class="voice-panel"><div class="voice-top"><button id="voiceBack" class="voice-back">← 戻る</button><div id="voiceProgress" class="voice-progress"></div></div><div class="voice-kicker">VOICE SHADOWING</div><div class="voice-title">声出し暗記</div><div class="voice-lead">決まり字を見たら、下の句を口から出す。<br>見る → 一緒に言う → 隠して言う、の3ステップ。</div><div id="voicePlay"><div class="voice-card"><div id="voiceStep" class="voice-step"></div><div id="voiceKey" class="voice-key"></div><div class="voice-arrow">↓</div><div id="voiceLower" class="voice-lower"></div><div id="voiceCue" class="voice-cue"></div><div id="voiceTimer" class="voice-timer"></div></div><div id="voiceActions" class="voice-actions"></div><div class="voice-note">音声認識は使いません。声に出したあと、自分で「言えた／あやしい／言えない」を判定します。</div></div><div id="voiceSummary" class="voice-summary"><div class="voice-kicker">SESSION COMPLETE</div><div class="voice-big" id="voiceBig">7枚</div><div id="voiceStats" class="voice-stats"></div><div id="voiceReview" class="voice-review"></div><button id="voiceAgain" class="voice-main">もう一度</button><button id="voiceHome" class="voice-main gold" style="margin-top:8px">設定へ戻る</button></div></div>`;document.querySelector('.app').appendChild(page);
$('#voiceBack').onclick=exitVoice;$('#voiceAgain').onclick=startVoice;$('#voiceHome').onclick=exitVoice}
function installEntry(){const start=$('#startScreen .panel');if(!start||$('#voiceEntry'))return;const b=document.createElement('button');b.id='voiceEntry';b.className='voice-entry';b.textContent='🗣 声出し暗記';const dash=$('#dashBtn');if(dash)start.insertBefore(b,dash);else start.appendChild(b);b.onclick=startVoice}
function showVoice(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));page.classList.add('active')}
function exitVoice(){clearTimeout(autoTimer);page.classList.remove('active');$('#startScreen').classList.add('active')}
function startVoice(){clearTimeout(autoTimer);queue=base().map(p=>({p,repeat:false}));index=0;results={};requeues={};$('#voiceSummary').classList.remove('show');$('#voicePlay').style.display='block';showVoice();nextCard()}
function nextCard(){if(index>=queue.length){finishVoice();return}current=queue[index];phase='see';renderPhase()}
function setActions(html){$('#voiceActions').innerHTML=html}
function renderPhase(){const p=current.p;$('#voiceProgress').textContent=`${Math.min(index+1,7)} / 7${current.repeat?'・復習':''}`;$('#voiceKey').textContent=p.key;$('#voiceTimer').textContent='';if(phase==='see'){ $('#voiceStep').textContent='STEP 1　見る';$('#voiceLower').className='voice-lower';$('#voiceLower').textContent=shortLower(p);$('#voiceCue').textContent='まず、決まり字と下の句をセットで見ます';setActions('<button id="vNext" class="voice-main">声に出す →</button>');$('#vNext').onclick=()=>{phase='shadow';renderPhase()};}
else if(phase==='shadow'){ $('#voiceStep').textContent='STEP 2　一緒に言う';$('#voiceLower').className='voice-lower';$('#voiceLower').textContent=shortLower(p);$('#voiceCue').textContent=`「${p.key} → ${clean(p.lower).slice(0,7)}…」と声に出してください`;setActions('<button id="vNext" class="voice-main gold">隠して言う →</button>');$('#vNext').onclick=()=>{phase='recall';renderPhase()};}
else if(phase==='recall'){ $('#voiceStep').textContent='STEP 3　思い出して言う';$('#voiceLower').className='voice-lower masked';$('#voiceLower').textContent='・・・・・・・・・・・';$('#voiceCue').textContent=`「${p.key} → ？」 声に出して思い出そう`;let sec=3;$('#voiceTimer').textContent=`答えを見るまで ${sec}`;setActions('<button id="vReveal" class="voice-main">答えを見る</button>');$('#vReveal').onclick=()=>reveal();autoTimer=setInterval(()=>{sec--;if(sec>0)$('#voiceTimer').textContent=`答えを見るまで ${sec}`;else{clearInterval(autoTimer);reveal()}},1000)}
else if(phase==='rate'){ $('#voiceStep').textContent='SELF CHECK';$('#voiceLower').className='voice-lower';$('#voiceLower').textContent=shortLower(p);$('#voiceCue').textContent='今、見ないで言えましたか？';$('#voiceTimer').textContent='';setActions('<div class="voice-self"><button class="yes" data-rate="yes">◎ 言えた</button><button class="maybe" data-rate="maybe">△ あやしい</button><button class="no" data-rate="no">× 言えない</button></div>');document.querySelectorAll('.voice-self button').forEach(b=>b.onclick=()=>rate(b.dataset.rate));}}
function reveal(){if(phase!=='recall')return;clearInterval(autoTimer);phase='rate';renderPhase()}
function rate(r){const p=current.p;results[p.key]=r;if(r==='no'&&!current.repeat&&!requeues[p.key]){requeues[p.key]=1;const pos=Math.min(queue.length,index+3);queue.splice(pos,0,{p,repeat:true})}else if(r==='maybe'&&!current.repeat&&!requeues[p.key]){requeues[p.key]=1;const pos=Math.min(queue.length,index+4);queue.splice(pos,0,{p,repeat:true})}index++;nextCard()}
function finishVoice(){const keys=base().map(p=>p.key),yes=keys.filter(k=>results[k]==='yes').length,maybe=keys.filter(k=>results[k]==='maybe').length,no=keys.filter(k=>results[k]==='no'||!results[k]).length;$('#voicePlay').style.display='none';$('#voiceSummary').classList.add('show');$('#voiceBig').textContent=`${yes} / 7`;$('#voiceStats').innerHTML=`<div class="voice-stat"><b>${yes}</b><span>言えた</span></div><div class="voice-stat"><b>${maybe}</b><span>あやしい</span></div><div class="voice-stat"><b>${no}</b><span>言えない</span></div>`;const rv=$('#voiceReview');rv.innerHTML='';keys.forEach(k=>{const d=document.createElement('div');d.className='voice-dot '+(results[k]==='yes'?'ok':results[k]==='maybe'?'mid':'ng');d.textContent=k;rv.appendChild(d)})}
function init(){if(!window.QUESTION_POOL||!$('#startScreen')){setTimeout(init,100);return}injectStyles();makePage();installEntry()}
init();
})();